"""update client_account column address and phone

Revision ID: f8e96074bfa7
Revises: ae6346ce3d65
Create Date: 2020-11-22 01:47:58.083402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e96074bfa7'
down_revision = 'ae6346ce3d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_account_address', table_name='client_account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_client_account_address', 'client_account', ['address'], unique=1)
    # ### end Alembic commands ###
